### PR TITLE
added CSV and PDF output

### PR DESCRIPTION
**Pull request by fpom**
I ported to `copydetect` something I previously developed for [`mousse`](https://github.com/fpom/mousse): the generation of a clickable PDF heatmap. It's like the similarity matrix `copydetect` already has in its report, but with similar files clustered together, and with dots clickable to open the report on the corresponding match. I've also added an option to save the similarity matrix as a CSV file. Essentially, the changes are as follows:
 * rename `out_file` to `html_file` everywhere which allows a uniform treatment with new `pdf_file` and `csv_file`
 * new methods to class `CopyDetector` and new init parameters
 * new options to CLI and their processing
 * new JavaScript in `report.html` to expand the match and scroll to it when `#collapse-num` is found in the URL
 * new dependencies (`pandas`, `scipy`, and `seaborn`)

### CODE REVIEW

**Comment by blingenf** [comment]
Cool! I'll take a closer look at the code sometime soon (I think the tests are probably still using `out_file` and failing as a result) but the PDF and CSV files look really nice.

**Comment by fpom** [comment]
Oh, sorry, I completely forgot to check the tests.

**Comment by blingenf** [comment]
It looks like the tests are failing due to issues introduced with API usage. I believe the following two changes should fix this:
1. Add `out_file` parameter back to `CopyDetector` constructor, but with a deprecation warning (similar to what I have for the `config` argument):
```python
if out_file is not None:
    warnings.warn(
        "The out_file parameter is deprecated and will be removed "
        "in a future version. Use the html_file parameter to "
        "specify an HTML output file.",
        DeprecationWarning, stacklevel=2
    )
    html_file = out_file
````
Changing the parameter names in the tests to `html_file` would also work, but retaining the option with a deprecation warning will avoid immediately breaking any code which is relying on the `out_file` parameter in the API.

2. The other issue is that setting default values for the csv and pdf paths in `__main__.py` means that these end up as `None` for API usage (that's what's causing most of the test failures). Moving the setting of default values into the `CopyDetector` constructor should fix this.

I'm also thinking that output paths should probably be arguments to the specific `generate_*_report()` functions rather than parameters to the class itself. In a very early version of copydetect I was saving cache files to the output folder during similarity computation so it made sense for this to be a class variable. With the current design it probably no longer makes sense. But these two fixes should be good enough for now, I can deal with the path situation in a separate PR.

**Comment by fpom** [comment]
Regarding (1), I've added back `out_file` in addition to `html_file`, and a warning is issued as you recommended. The idea for having both is that issuing a deprecation warning on `out_file` makes no sense in one cannot use `html_file` instead.

But I don't understand (2), perhaps because I did not completely get how `config` interacts with parameters. So far, `pdf_file` and `csv_file` are set in `__main__` from `out_file` because they are just Boolean options. And the constructor of `CopyDetector` does the same if they are left to `None`. The reason why I did not want file name options is that the PDF report has to give clickable links to the HTML report, and I feel that it is probably simpler and more understandable for users to have both files together in the same directory. The API gives more flexibility, but it's intended for users that know a bit better what they do.

I've also simplified heatmap generation, in particular, I've removed the pruning of non-relevant pairs: in most cases, it did not remove so much and could break when using both `-t` and `-r` options. I will try other ways to produce simplified and more readable heatmaps, I have some ideas.

I like the idea to move file name options to `generate_*_report` methods, we just have to take care that we cannot generate a PDF with clickable links if the HTML report is not also generated. Perhaps `generate_html_report` could set an attribute with the path of the generated file, then, if `generate_pdf_report` does not see this attribute, it could either call `generate_html_report` or give up adding clickable links (which could be controlled with an option).

**Comment by blingenf** [comment]
Sorry, I should have been a little more specific about (2) -- I think the way you designed these parameters for the CLI makes perfect sense. The issue is that the code in `_check_arguments()` assumes that `html_file`, `pdf_file`, and `csv_file` are all valid. If they are not provided, the code will crash (this was also causing some of the test failures). So for example, the API demonstration in [README.md](https://github.com/blingenf/copydetect#api) would result in an immediate crash because pdf/csv file aren't defined:
```python
>>> from copydetect import CopyDetector
>>> detector = CopyDetector(test_dirs=["tests"], extensions=["py"],
...                         display_t=0.5)
Traceback (most recent call last):
  File "/home/bryson/Documents/copydetect/copydetect/detector.py", line 290, in __init__
    self._check_arguments()
  File "/home/bryson/Documents/copydetect/copydetect/detector.py", line 426, in _check_arguments
    if not Path(getattr(self, f"{ext}_file")).parent.exists():
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Setting defaults within `CopyDetector` instead of `__main__.py` was the first solution to this problem that I thought of but allowing `pdf_file` and `csv_file` to be `None` would also work (though that would mean a crash would be expected if `generate_csv_report` or `generate_pdf_report` is called). I basically just want to avoid a new version of copydetect immediately breaking the code of any project using its API.

**Comment by fpom** [comment]
Thank you for your explanation. I moved the call to `_check_argument` just after initialising `pdf_file` and `html_file`. It should work now, at least, the example you gave me works.

**Comment by blingenf** [comment]
Two of the tests were failing due to `html_file` not being set so I slightly changed how the deprecated parameter is managed. All test are now passing. I want to do a quick bug fix release first but I'll get this merged in soon.

**Comment by fpom** [comment]
Thanks for your help! I've run `python tests/test_detector.py`, and it did not report any problem. How do you run your tests? I'm currently working on splitting the heatmaps so they are more readable, and I also improved the sizing and positioning of the clickable links. I'd be happy to detect problems myself and submit pull requests easier to merge.

**Comment by blingenf** [comment]
I'm using pytest for testing. You should be able to run `pytest` in the project root after installing the local copydetect version with your changes using pip.

```
~/Documents/copydetect$ pytest
================================= test session starts =================================
platform linux -- Python 3.8.8, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/bryson/Documents/copydetect
plugins: anyio-2.2.0
collected 37 items                                                                    

tests/test_detector.py .............                                            [ 35%]
tests/test_pywinnowing.py ......                                                [ 51%]
tests/test_sanity_checks.py ..                                                  [ 56%]
tests/test_utils.py ..........                                                  [ 83%]
tests/test_winnowing.py ......                                                  [100%]
=========================== 37 passed, 4 warnings in 3.23s ============================
```
I changed the target branch from `master` to `develop` before merging -- that way I can push bug fixes to master if needed before the next major version release. So if you're working on additional changes just PR those to `develop` then I'll merge `develop` into `master` when I'm ready to include everything in a PyPI release.

**Comment by fpom** [comment]
Thanks!

**Pull request merged**
